version: "3.9"
services: 
    php:
        build: .
        restart: always
        volumes: 
            - ./:/var/www/html
        ports: 
            - 8080:80
        links: 
            - mariadb

    
    mariadb:
        image: "mariadb:latest"
        restart: always
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
    
    myadmin:
        depends_on: 
            - mariadb
        image: "phpmyadmin:latest"
        restart: always
        ports: 
            - 8000:80
        environment:
            - PMA_HOST=mariadb
        
    
    